pipeline {
    agent any

    environment {
        AWS_EC2_HOST = 'ec2-3-15-235-93.us-east-2.compute.amazonaws.com'
        AWS_EC2_USER = 'ec2-user'
        AWS_EC2_KEY = credentials('ec2-key')
        JAR_FILE = 'target/airline-management-0.0.1-SNAPSHOT.jar'
        MAVEN_HOME = 'C:\\Users\\harsh\\apache-maven\\apache-maven-3.9.9'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat """
                    "%MAVEN_HOME%\\bin\\mvn" clean package -DskipTests
                """
            }
        }

        stage('Test') {
            steps {
                bat """
                    "%MAVEN_HOME%\\bin\\mvn" test
                """
            }
            post {
                always {
                    junit '**/target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-key']) {
                    bat """
                        scp -o StrictHostKeyChecking=no %JAR_FILE% %AWS_EC2_USER%@%AWS_EC2_HOST%:/home/%AWS_EC2_USER%/app/
                    """
                }
            }
        }

        stage('Start Application') {
            steps {
                sshagent(['ec2-key']) {
                    bat """
                        ssh -o StrictHostKeyChecking=no %AWS_EC2_USER%@%AWS_EC2_HOST% "pkill -f \\"java -jar\\" || true && nohup java -jar /home/%AWS_EC2_USER%/app/%JAR_FILE% > app.log 2>&1 &"
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
